[package]
name = "rustcraft"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mc-varint = "0.1.1"
serde = { version = "1.0", features = ["derive"]}
serde_json = "1.0"
openssl = "0.10"
rand = "0.8"